name: Build Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-24.04${{matrix.arch=='arm64' && '-arm' || ''}}
    strategy:
      fail-fast: false
      matrix:
        arch: [ 'amd64', 'arm64' ]
    steps:

      - name: run
        run: |
          sudo apt-get update -y && apt-get install -y strace r-base ghostscript --no-install-recommends
          gs --version #10.02.1
          strace -o foo -f R -e "bitmap('test.bmp')" || true
      - name: upload
        uses: actions/upload-artifact@v6
        with:
          path: foo
